#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Package-Constants
Version  : 0.06
Release  : 25
URL      : https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Package-Constants-0.06.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Package-Constants-0.06.tar.gz
Summary  : 'List constants defined in a package'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Package-Constants-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
list all constants defined in a package.
Please refer to 'perldoc Package::Constants' after installation for
details.

%package dev
Summary: dev components for the perl-Package-Constants package.
Group: Development
Provides: perl-Package-Constants-devel = %{version}-%{release}
Requires: perl-Package-Constants = %{version}-%{release}

%description dev
dev components for the perl-Package-Constants package.


%package perl
Summary: perl components for the perl-Package-Constants package.
Group: Default
Requires: perl-Package-Constants = %{version}-%{release}

%description perl
perl components for the perl-Package-Constants package.


%prep
%setup -q -n Package-Constants-0.06
cd %{_builddir}/Package-Constants-0.06

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Package::Constants.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
